language: python
python:
  - "2.7"


sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - TARGETS="aarch64 armv5e armv7a-neon mips64 core2-64 i586"
        - YP_RELEASE=2.1
        - ZEPHYR_RELEASE=0.7.5
        - OSTRO_RELEASE=v1.0.0
        - CROPS_RELEASE=latest
        - secure: "KqXmjeziyC0cjvfgOczSn6yFmfucHW9fBpGjHnq+Fzcb3CTrBX4US/fmbCVBySwZFZd1EF3/+Nhlno/9U4Wt8V9WipZxMiYZwh8c/tsSABZG+eyN6s1zKcd6LIJqBXMpN4fn1SQ9Mky9jHKbLUPNd+b1cqoLiE4WLl+lnqYfPqW46j1SA2tVmBy4gvf6pCWB/NmF94ueZxjfXg488Z0z8hf72xhLFEBgk+RZjr6sw3u5iAyEPbzbZKE/x5VHN5wLI9KbNEBEZs0Hh8MSZceaIB/3rThrJUT97nWUxJa5dHk0Xiyqf7yoyPvixEVCVxoY6pZkmKfeItQi2ZP13QIIYCksbQ3alSv1GjEenFEhq027w89Zw0772zTFq2zlWPgfyjvIvz7f0AR2P5nInG90BAvx5gjMVhZmxl/9Z9e4Y+Chakm4NeWcjG33yxY8I6tBP7zE3iiCDv5XLp2rOAtl/RDKhDRxHoxO/Gxi5OSI8SfjU+Jc24GflL0akFSsoQ5hfJSLiTVOLn5DpP0IYZ4ao9Cpv8mkyHEpK3LKxsz0w6tWEGNpx3QJahXwEEphP3P3ld+RWMnXD655Brio6wVTskRSHy6on/aCTfDQy0I1jdqhqdCym1MUDPiLKi7tczkSnHtOtIij2amHZ685mcY4ZhGjfR4f+uFkHUoWsDOFYW4="  # DOCKER_EMAIL_bavery
        - secure: "hxToHr4JAxnMha79z16IXfk8alYxzrFzPZHB/Hul+YuuucF9kqeJVn98eLX+aGK9PpOktYCyvWwIWEVGAXy6AKwzYH3zSY/OQCkC5vmijsHNZ2Z63nQ9H4PQot1SS10RDcAcuAUfDeZtZZ1Ktngaykb0tQGcwmkoHIrbHuDQN+IRWw2l8xxpgWXE9G5HOj60Lj/+boL/ybMsXwbLjqwDUuBYLT/bUZELMZS1KZaDI+0R3yObnrfMtG876jXoUXGfoEswKWiUmYxv5BvyQORNzhRmBipRpi4wTZ0xszbWzWxjXylME/TDVnrvDUBxS+plgDTkLk/znKQbqsELcTbS/Rh/ZfEk+/AFeLLIs+ObxkHWJ7Ib5L4Uiyx7fABu8ym2fPr6EWqR0M2zaVZQA5bBrWXkaQWFM9iAAUbhnMWaB7+zZUmGjdrHhHNKP68OS2tYgj7iY4vexB298Jq8Ej8o+SQkFpMZfU/PiaXJVEnwzgnqNJFDX+WpFglW+rxwkmxDvP/7ds4soGEpqU5C4t6+YsbXoRJjRVVtBmNDZ6a50BcvQA2lctIOJkwGSwu8HrYPdQv9C64URZT9TRYe7IUIgiwWOsWVoOQBD/zkDusmAGso78D6Dxt0s6LZFpA8pvy7K+UeuFNI8Sgnl5n/nD9oMSjeARN7rYVB2mluVJKzbng="  # DOCKER_PASS_bavery



compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}


script:
  - docker version
  - echo "set Docker Repo"
  - source ./scripts/setDockerhubRepo.sh
  - echo "Building Base"
  - chmod 777 ./scripts/build_containers.base
  - ./scripts/build_containers.base
  - python tests.py
  - chmod 777 ./scripts/pushToDockerhub.sh
  - ./scripts/pushToDockerhub.sh





notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
